### ISSUE TITLE
pytorch的crnn训练中出现问题

### ISSUE THREAD

**Issue by infinitisun** [xiaofengShi/CHINESE-OCR#17]
pytorch训练过程中，会在utils.py里的encode()函数卡住，不停迭代
    def encode(self, text, depth=0):
        """Support batch or single str."""
        if isinstance(text, str):
            text = [self.dict[char.lower()] for char in text]
            length = [len(text)]
        if isinstance(text, str):
            text = [self.dict.get(char, 0) for char in text]
            length = [len(text)]
            ######## add for unicode
        # elif isinstance(text, unicode):
        #     text = [self.dict.get(char, self.dict[u'-']) for char in text]
        #     length = [len(text)]
        elif isinstance(text, collections.Iterable):
            length = [len(text)]
            print(length)  #试着打印这个length 会一直增加
            text = ''.join(str(v) for v in text)
            text, _ = self.encode(text)
        if depth:
            return text, len(text)
        return (torch.IntTensor(text), torch.IntTensor(length))

这个函数是有什么问题吗？@xiaofengshi

**Comment by infinitisun** [comment]
keras的训练没什么问题 但是从output来看 有过拟合的现象

**Comment by Cony07f5** [comment]
我keras训练crnn总是报 raise ValueError(err.message)
ValueError: Shape must be rank 1 but is rank 4 for 'batch_normalization_1/cond/FusedBatchNorm' (op: 'FusedBatchNorm') with input shapes: [?,4,?,512], [1,4,1,1], [1,4,1,1], [1,4,1,1], [1,4,1,1].
这个错误，请问你有遇到过吗？

**Comment by Cony07f5** [comment]
@18813055625 加你QQ了
我weixin pop0fa

**Comment by CNU105** [comment]
我也是pytorch训练的过程中卡住

**Comment by ooooverflow** [comment]
@infinitisun 请问老哥解决没有啊，我也是定位到这个encode函数发现一直在迭代啊

**Comment by CNU105** [comment]
我是把原来的encode函数改成了下面这样，然后这个地方过去了但是又超出显存。。。
    def encode(self, text, depth=0):
        """Support batch or single str.

        Args:
            text (str or list of str): texts to convert.

        Returns:
            torch.IntTensor [length_0 + length_1 + ... length_{n - 1}]: encoded texts.
            torch.IntTensor [n]: length of each text.
        """
        length = []
        result = []
        for item in text:
            if self.is_chinese(item):
                item = item.encode('utf-8')
            length.append(len(item))
            for char in item:
                index = char
                result.append(index)
        text = result
        length = [len(length)]

        return (torch.IntTensor(text), torch.IntTensor(length))

**Comment by CNU105** [comment]
我是把原来的encode函数改成了下面这样，但是又超出了显存。。。
`    def encode(self, text, depth=0):
        """Support batch or single str.

        Args:
            text (str or list of str): texts to convert.

        Returns:
            torch.IntTensor [length_0 + length_1 + ... length_{n - 1}]: encoded texts.
            torch.IntTensor [n]: length of each text.
        """
        length = []
        result = []
        for item in text:
            if self.is_chinese(item):
                item = item.encode('utf-8')
            length.append(len(item))
            for char in item:
                index = char
                result.append(index)
        text = result
        length = [len(length)]

        return (torch.IntTensor(text), torch.IntTensor(length))`

**Comment by qq542288564** [comment]
@CNU105  我也是卡住了，  一直循环，根据你改了encode函数好像也卡在那里哦，你现在解决了吗

**Comment by qq542288564** [comment]
@CNU105 @infinitisun 你们怎么解决的啊  我也卡在了 无限循环哦   改了def encode(self, text, depth=0)方法又会报其他的错误哦

**Comment by Fish-wangyang** [comment]
有没有解决方法啊？急急急

**Comment by psw13583112** [comment]
我把代码改成下面这样就可以运行了

def encode(self, text, depth=0):
        """Support batch or single str."""
        if isinstance(text, str):
            text_out = [self.dict.get(char, 0) for char in text]
            length = [len(text)]

        elif isinstance(text, collections.Iterable):
            length = [len(text)]
            text_out = ''.join(str(v) for v in text)
            text_out, _ = self.encode(text_out)

        if depth:
            return text_out, len(text_out)
        return (torch.IntTensor(text_out), torch.IntTensor(length))
