### ISSUE TITLE
'NoneType' object has no attribute 'model_checkpoint_path'

### ISSUE THREAD

**Issue by Wini1680** [xiaofengShi/CHINESE-OCR#19]
您好，我在运行demo.py的时候出现的这个问题一直没有找到，请问有跑通的同胞们分享以下怎么解决这个问题呢？
`File "/home/xshine6/Downloads/CHINESE-OCR/ctpn/ctpn/model.py", line 37, in load_tf_model
    reader = tf.train.NewCheckpointReader(ckpt.model_checkpoint_path)
AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'`

**Comment by Wini1680** [comment]
该了下checkpoint的路径就好了

**Comment by pengcao** [comment]
CHINESE-OCR-master\ctpn\ctpn\model.py中的
/Users/xiaofeng/Code/Github/dataset/CHINESE_OCR/ctpn/ctpn_checkpoints/ 改成
/opt/CHINESE-OCR-master/ctpn/checkpoints/（这个根据md文件中的下载路径进行下载即可得到）

**Comment by OKhyc** [comment]
不知道该怎么办了  我也已经改成/opt/CHINESE-OCR-master/ctpn/checkpoints/  了  还是这个错，太累了
