### ISSUE TITLE
下了checkpoints权重，但是'NoneType' object has no attribute 'model_checkpoint_path'

### ISSUE THREAD

**Issue by Hjy20255** [xiaofengShi/CHINESE-OCR#43]
下了checkpoints权重，但是'NoneType' object has no attribute 'model_checkpoint_path'

**Comment by Hjy20255** [comment]
已经解决  路径问题

**Comment by mangoHoli** [comment]
> 已经解决 路径问题

路径我也改了，还是不行呢

**Comment by IcyW** [comment]
同问：
`
reader = tf.train.NewCheckpointReader(ckpt.model_checkpoint_path)
AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'
`
看到脚本里是：
`ckpt_path = '/Users/xiaofeng/Code/Github/dataset/CHINESE_OCR/ctpn/ctpn/retrain/ckpt'`

应该在哪里下载模型?
