### ISSUE TITLE
oc4的预训练模型是否不是用trainbatch.py训练出来的？

### ISSUE THREAD

**Issue by Jamsa** [xiaofengShi/CHINESE-OCR#7]
在训练自己的模型的时候（keys修改过）发现得到的结果总是00或000。
是否预训练模型不是用trainbatch.py训练出来的？

我用的是keras的ocr代码，里面对样本的处理存在以下差异：
 1. ocr/model.predict方法只是把图像resize为`(32,width)`，之后reshape为`(32,width,1)`，将数据处理为0，1之间。

 1. 而trainbatch.py和dataset.py中会在resize后把数据reshape为`(-1,32,256,1)`。之后处理为0，1之间之后，再减0.5，再除0.5。

 1. train.py中是`Length = int(imgW/4)-1`，trainbatch.py中是`Length = int(imgW/4)-2`

这样trainbatch.py，train.py和ocr/model.predict三个地方的对样本的处理方式不是都不同吗？好像只有allinonetrain.py与trainbatch.py一致。

是因为这个原因导致我用自己的keys.py训练的时候总是得不到想要的效果吗？

**Comment by Jamsa** [comment]
找出问题了，是我样本的宽度小于256，大概不到160，我把imgW调为160后正常。

ocr/model.predict还是存在问题的，改成与训练样本一样，效果会更好一些。我训练纯数字的情况下，如果不改，会有部分数字识别错误：

```python
img = np.array(im).astype(np.float32) / 255.0
X = img.reshape((32, w, 1))
X = np.array([X])
```
改为
```python
img = (np.array(im).astype(np.float32) / 255.0-0.5)/0.5
X = img.reshape((-1,32, w, 1))
```

**Comment by HuiHuangEmi** [comment]
@Jamsa 请问如果我的训练数据不定长，单个字符到十几个字符都有，这样训练的时候resize是不是就失真了？需要在较短的图片后面增加空白像素么？
