### ISSUE TITLE
请问crnn pytorch能训练吗

### ISSUE THREAD

**Issue by ccnankai** [xiaofengShi/CHINESE-OCR#9]
hi @xiaofengShi 
为什么crnn  显示了网络结构之后 ，一直卡住不动？请问你的用Python3能训练吗？

**Comment by xxllp** [comment]
作者的代码应该是针对2的

**Comment by ccnankai** [comment]
@xxllp   知道了 ，多谢多谢 ，我自己改下

**Comment by xxllp** [comment]
@ccnankai 你有跑成功嘛

**Comment by ccnankai** [comment]
@xxllp  还没改完，编码有点问题

**Comment by Wini1680** [comment]
@ccnankai 我这也卡在这，请问您是怎么解决的呢？是不是数据集的问题？
